void S12_chiSquareHist_LanGaus_9d()
{
//=========Macro generated from canvas: c/c
//=========  (Thu May 14 19:49:56 2020) by ROOT version 6.12/04
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->SetHighLightColor(2);
   c->Range(0.06249999,-0.65625,1.9375,5.90625);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
   
   TH1D *name__1 = new TH1D("name__1","9d, station 12",75,0.25,1.75);
   name__1->SetBinContent(24,1);
   name__1->SetBinContent(29,1);
   name__1->SetBinContent(30,3);
   name__1->SetBinContent(31,1);
   name__1->SetBinContent(32,1);
   name__1->SetBinContent(33,1);
   name__1->SetBinContent(34,1);
   name__1->SetBinContent(35,3);
   name__1->SetBinContent(36,2);
   name__1->SetBinContent(37,4);
   name__1->SetBinContent(38,4);
   name__1->SetBinContent(39,3);
   name__1->SetBinContent(40,4);
   name__1->SetBinContent(41,3);
   name__1->SetBinContent(42,4);
   name__1->SetBinContent(43,5);
   name__1->SetBinContent(44,2);
   name__1->SetBinContent(45,2);
   name__1->SetBinContent(46,1);
   name__1->SetBinContent(47,1);
   name__1->SetBinContent(48,1);
   name__1->SetBinContent(57,1);
   name__1->SetEntries(49);
   
   TPaveStats *ptstats = new TPaveStats(0.11,0.69,0.49,0.89,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetLineWidth(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("Mean  =  1.018 #pm 0.01643");
   ptstats_LaTex->SetTextSize(0.046);
   ptstats_LaTex = ptstats->AddText("Std Dev   =  0.115 #pm 0.01161");
   ptstats_LaTex = ptstats->AddText("Underflow =      0");
   ptstats_LaTex = ptstats->AddText("Overflow  =      0");
   ptstats->SetOptStat(112200);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   name__1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(name__1);
   name__1->SetLineWidth(3);
   name__1->GetXaxis()->SetTitle("#chi^{2}/NDF");
   name__1->GetXaxis()->CenterTitle(true);
   name__1->GetXaxis()->SetLabelFont(42);
   name__1->GetXaxis()->SetLabelSize(0.035);
   name__1->GetXaxis()->SetTitleOffset(1.1);
   name__1->GetXaxis()->SetTitleFont(42);
   name__1->GetYaxis()->SetTitle("Fits");
   name__1->GetYaxis()->CenterTitle(true);
   name__1->GetYaxis()->SetNdivisions(4000510);
   name__1->GetYaxis()->SetLabelFont(42);
   name__1->GetYaxis()->SetLabelSize(0.035);
   name__1->GetYaxis()->SetTitleOffset(1.1);
   name__1->GetYaxis()->SetTitleFont(42);
   name__1->GetZaxis()->SetLabelFont(42);
   name__1->GetZaxis()->SetLabelSize(0.035);
   name__1->GetZaxis()->SetTitleSize(0.035);
   name__1->GetZaxis()->SetTitleFont(42);
   name__1->Draw("");
   
   ptstats = new TPaveStats(0.11,0.69,0.49,0.89,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetLineWidth(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   ptstats_LaTex = ptstats->AddText("Mean  =  1.018 #pm 0.01643");
   ptstats_LaTex->SetTextSize(0.046);
   ptstats_LaTex = ptstats->AddText("Std Dev   =  0.115 #pm 0.01161");
   ptstats_LaTex = ptstats->AddText("Underflow =      0");
   ptstats_LaTex = ptstats->AddText("Overflow  =      0");
   ptstats->SetOptStat(112200);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
